# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.7
_src_path: https://github.com/jupyterlab/extension-template
author_email: pbement@phas.ubc.ca
author_name: pbement
has_binder: false
has_settings: true
kind: frontend
labextension_name: llm_complete
project_short_description: A JupyterLab extension.
python_name: llm_complete
repository: ''
test: false

